// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjAZ_HTNBNSl3dwonLrHzvFPAwsSnw_w',
    appId: '1:318226051372:web:ec0de5554698ef514c3c89',
    messagingSenderId: '318226051372',
    projectId: 'proyectdriveme',
    authDomain: 'proyectdriveme.firebaseapp.com',
    storageBucket: 'proyectdriveme.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6LctaWMhKPQ4YO-Qx_tdY067w20MkQXU',
    appId: '1:318226051372:android:cb882f5abc7ce44c4c3c89',
    messagingSenderId: '318226051372',
    projectId: 'proyectdriveme',
    storageBucket: 'proyectdriveme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsjDPE-JnIT48EntBIg8b0y6vj41A2TLo',
    appId: '1:318226051372:ios:0c01addfd0bedb624c3c89',
    messagingSenderId: '318226051372',
    projectId: 'proyectdriveme',
    storageBucket: 'proyectdriveme.firebasestorage.app',
    androidClientId:
        '318226051372-kimjcfcrbbsdeinst4srgo27e2gj7dv3.apps.googleusercontent.com',
    iosClientId:
        '318226051372-unbgsvb8c5ltrv2dvv7nscph01idkkuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveMeApplicationV02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsjDPE-JnIT48EntBIg8b0y6vj41A2TLo',
    appId: '1:318226051372:ios:0c01addfd0bedb624c3c89',
    messagingSenderId: '318226051372',
    projectId: 'proyectdriveme',
    storageBucket: 'proyectdriveme.firebasestorage.app',
    androidClientId:
        '318226051372-kimjcfcrbbsdeinst4srgo27e2gj7dv3.apps.googleusercontent.com',
    iosClientId:
        '318226051372-unbgsvb8c5ltrv2dvv7nscph01idkkuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveMeApplicationV02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6tysTocKDOkCls3k6argwqTJIKUhYtf8',
    appId: '1:318226051372:web:36bd332912930c704c3c89',
    messagingSenderId: '318226051372',
    projectId: 'proyectdriveme',
    authDomain: 'proyectdriveme.firebaseapp.com',
    storageBucket: 'proyectdriveme.firebasestorage.app',
  );
}
